"""initial migration

Revision ID: 1ef3952517a6
Revises: 
Create Date: 2018-08-30 13:17:26.605881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef3952517a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('kissa', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles") as batch_op:
        batch_op.drop_column('kissa')
    # ### end Alembic commands ###
